### ISSUE TITLE
Bug: custom_appBar의 Navigator 기능 미작동

### ISSUE THREAD

**Issue by ima9ine4** [TEAM-LINRING/LINRING-FRONT-FLUTTER#8]
**✍ Description**
`Widget` 으로 분류한 `appBar` 에 대해서 `Navigator` 가 작동하지 않습니다.

**📋 How to...**
아래와 같은 방법으로 뒤로가기가 작동하지 않음을 확인하면 됩니다.
1. 시뮬레이터를 실행시켜 첫 화면을 띄운다.
2. 회원가입 페이지로 이동한다.
3. 상단 앱바 좌측에 위치한 뒤로가기 모양 아이콘을 누른다.

**Comment by Choi-Jiwon-38** [comment]
*문제 상황 공유*
- 현재 `CustomAppBar`의 뒤로가기 기능에서 참조하고 있는 `context`는 `CustomAppBar` 자신의 페이지에 대한 컨텍스트에 해당됨.
- `CustomAppBar`를 각 페이지의 `appBar`로 사용하기 위해서는 각 페이지의 컨텍스트를 참조하도록 수정이 필요함.
